language: node_js
node_js: 12
stages:
- testing
- deployment
jobs:
  include:
  - name: UnitTest
    stage: testing
    install: npm install
    script: npm run test

deploy:
  provider: heroku
  api_key:
    secure: iLXD1r+X3R1QDVHME/ETurOVvqF2x8WoJfEZ1ssnDl2xknIQCciF1Y5Z4oMMeJfICIJVgLMuGQbNwZqaqUkJLvZzfF/0lbERijzfJEIWfEK2FHBAINBxonQWQe1TrK/CV4EUy4/MWhOOxTjCFc8kXfk8JDHPehVK4NHp1nCTC8FBh4RqdXYyfOqprZZk0XVy+NNyZtq8Hasw7NaUfHObCum/EQqN6LK20XOqohXqnAor8y6kvzuf3BI6tGNbMy2i8hImS6fj8hFsn02TgnzXKkIZT0Q81kxw2VMMhmR6dQfoK7a2L6ld8sBYJQI/MMh1Gzv9/B/7xfPqZk7H7XJQMbZx5/lGXdxcONRLB4+hSfjH0w5Rg5npIKGh88hBgT11Mxf9vEso1/zswX5Ds6j3sr+07+13X3JM1tACdVSszTW5M7aICsqIvTueWCiR8i449fbegTFA5Qyeqk5r78+affu6NGud1oSuYTFo3ZKgNrcwVEgWGqiL/RkbixVRlHJZnd+2RPqkmjAdUuXc7c2q+XRL3FaQ+gVwbs/7mZhf7Kc+ulgGysDAKOpfQ0Eo7FF21g3a1Tki3oSTN6YaA2Eh26rNB4CbZEYmxmf7ylkCB79RnWS6D3Ij0IavPrdcTkGGmGQoHNRqvztKxpyzxgylVnF8oCfjDsQSvLv/bIT8/CU=
